### ISSUE TITLE
High percentage of ambiguous bases.

### ISSUE THREAD

**Issue by keith-harrison** [bcgsc/ntJoin#107]
Hi I am trying to assemble genomes of other strains using another strains reference and am getting good matches from what I can see using mauve.
I first created contigs using flye and medaka.
However, I am now having the issue of a high N % in my assembly. Apologies if I have just missed a tool parameter!

`ntJoin assemble target=polished.fasta references=reference.fasta t=12 target_weight=1 reference_weights=2 n=2 w=250 k=32`
19% Ns
When I used homopolish after medaka this gave me 28% Ns.

**Comment by lcoombe** [comment]
Hi @keith-harrison,

By design, ntJoin is a scaffolding tool, meaning that it uses the structure of the reference assembly to scaffold together your target assembly. If two sequences joined are detected to have overlaps, then it will attempt to merge those sequences. Otherwise, sequences will be joined together with a gap (N's) between, with the length of that gap estimated using the reference.

So, that is why you are getting Ns in the final assembly - because the assembly is being scaffolded, with gaps being introduced between joins. Having a higher proportion of N's could be caused by a number of differences between the target at the reference, for example if the reference had a larger genome size, or if there were sequences in your target assembly that did not map well to the reference.

Some things to look at as indicators of the scaffolding would be the difference between the proportion of 'assigned' bases to 'unassigned' (these are separate fasta files that are concatenated as the last step of ntJoin) - to see if a large proportion of the target assembly could not be assigned/mapped properly to the reference.

Thank you for your interest in ntJoin - let me know if you have any other questions!
Lauren

**Comment by keith-harrison** [comment]
Thanks Lauren,
I had some good results when I used ntjoin and then used pilon with nanopore reads with --fix all (Ns went from 6.6% to 2.8% and busco from 89.4% to 94.1%). This got rid of the ambiguous bases well!
