### ISSUE TITLE
Output same as input

### ISSUE THREAD

**Issue by ViriatoII** [bcgsc/ntJoin#23]
Hi again,

So the program sounds great, but it's outputing the same as the input. I've tried many different k and w parameters, as well as different target assemblies and different number of references. 

Any idea of what might be wrong? Here goes a print of my last round.

```
Parameters:
        Reference TSV files:  ['B73v4.fa.k30.w500.tsv', 'CML247.fa.k30.w500.tsv']
        -s  scaffolded.scaffolds.fa.k30.w500.tsv
        -l  1.0
        -r  2 1
        -p  out.k30.w500.n1
        -n  1
        -k  30
        -g  20
        -t  1
        --agp
Orienting contigs using increasing/decreasing minimizer positions

2020-02-08 18:05:56.002096 : Reading minimizers B73v4.fa.k30.w500.tsv
2020-02-08 18:05:56.049081 : Reading minimizers CML247.fa.k30.w500.tsv
2020-02-08 18:05:56.093191 : Reading minimizers scaffolded.scaffolds.fa.k30.w500.tsv

Weights of assemblies:
B73v4.fa.k30.w500.tsv: 2.0
CML247.fa.k30.w500.tsv: 1.0
scaffolded.scaffolds.fa.k30.w500.tsv: 1.0

2020-02-08 18:05:56.197840 : Filtering minimizers
2020-02-08 18:05:56.211981 : Building graph
2020-02-08 18:05:56.215835 : Adding vertices
2020-02-08 18:05:56.215996 : Adding edges
2020-02-08 18:05:56.216303 : Adding attributes
2020-02-08 18:05:56.219615 : Printing graph out.k30.w500.n1.mx.dot

file_name       number  colour
B73v4.fa.k30.w500.tsv   0       red
CML247.fa.k30.w500.tsv  1       green
scaffolded.scaffolds.fa.k30.w500.tsv    2       blue

2020-02-08 18:05:56.229213 : Filtering the graph
2020-02-08 18:05:56.460025 : Reading fasta file scaffolded.scaffolds.fa
2020-02-08 18:05:56.507326 : Finding paths

Total number of components in graph: 1 

2020-02-08 18:05:56.529137 : Printing output scaffolds
2020-02-08 18:05:56.677655 : DONE!
touch scaffolded.scaffolds.fa.k30.w500.n1.assigned.scaffolds.fa
touch scaffolded.scaffolds.fa.k30.w500.n1.unassigned.scaffolds.fa
command time -v -o scaffolded.scaffolds.fa.k30.w500.n1.all.scaffolds.fa.time cat scaffolded.scaffolds.fa.k30.w500.n1.assigned.scaffolds.fa scaffolded.scaffolds.fa.k30.w500.n1.unassigned.scaffolds.fa > scaffolded.scaffolds.fa.k30.w500.n1.all.scaffolds.fa
```

The references are a 10 Mbps region in different genotypes of the same species. Ragoo was able to scaffold my target assembly based on these refs, but not in the cool way your program is written for.

Thank you for the attention,
Ricardo

**Comment by lcoombe** [comment]
Hi @ViriatoII,

Just to be sure, is the output PATH file and `assigned.scaffolds.fa` file empty? I added a test script last week (`tests/test_installation.sh`) that you could use to double check that your installation is working correctly.

As for what's going on if the installation is correct, how does the contiguity of your target assembly and the 'references' compare in that region of interest? 

Lauren

**Comment by ViriatoII** [comment]
Hey,

Thank you for the support!  The installation seems correct. The results of the test script are the same as the examples. 

The *.assigned.scaffolds.fa are not empty. They have 7 sequences (same number as the references?) and a ton of Ns.  In fact, I was wrong to say the final output is exactly the same as input, a couple of contigs have been scaffolded, but this was so minimal that I hadn't noticed.

My target input is a pacbio assembly that has already been a bit scaffolded (but I also tried it with the  unscaffolded version and with the corrected pacbio reads). Here are some statistics:
```
Contigs: 976
Contigs >= 5000 bps: 846
Contigs >= 10000 bps: 289
Contigs >= 100000 bps: 1
Largest contig: 105192
Total size: 9747441
Length >= 5000 bps: 9293534
Length >= 10000 bps: 5397670
Length >= 100000 bps: 105192
N50:10846
N90: 5580
L50: 239
L90: 748
Ns per 100 kbps: 1638.9429800088044
```

And this the output:
```
Contigs: 938
Contigs >= 5000 bps: 805
Contigs >= 10000 bps: 260
Contigs >= 100000 bps: 8
Largest contig: 2630826
Total size: 15360172
Length >= 5000 bps: 14900418
Length >= 10000 bps: 11090519
Length >= 100000 bps: 6905660
N50:27072
N90: 6197
L50: 29
L90: 613
Ns per 100 Kbps: 37580.86823506924
```


My references are the target region in different genotypes, they are each a single scaffold, albeit with Ns as well, ranging from 1000 Ns per 100 Kbps. It is very possible that several of my target contigs do not belong to the targeted region, but RaGoo managed to scaffold 700 across the alternative genotypes. 

What I would really like is to place these 700 contigs into one single scaffold based on the 7 references, and not place them in 7 scaffolds. I understood ntJoin does this.

**Comment by lcoombe** [comment]
Hi @ViriatoII,

It is possible that there are differences between the various references that are breaking up the graph. 
If each of the assemblies have a single scaffold across your region of interest, have you tried scaffolding your target assembly with just one of the references (say, the most contiguous one)? That would help to understand if the issue is differences between the references (perhaps we'd have to think about how to assign weights), or something between the target and a given reference.

**Comment by ViriatoII** [comment]
Good morning!

Using the most contiguous reference I get a single scaffold with 75494 Ns per 100 kbs (double of with more refs). This happens with ref_weight equal to 2, 3 and 4. Ref_weight=1 creates 30 scaffolds with 40 000 Ns per 100Kb, and also doesn't use 900 of my original scaffolds.

This differs from RaGoo that scaffolded 600 of them just using the best reference.

```
Contigs: 379
Contigs >= 5000 bps: 329
Contigs >= 100000 bps: 1
Largest contig: 6983724
Total size: 9807141
Length >= 5000 bps: 9638547
Length >= 100000 bps: 6983724
N50: 6983724
N90: 6854
L50: 1
L90: 192
Ns per 100 kbs:  2237

```

**Comment by lcoombe** [comment]
Glad to hear that you were able to get a single scaffold using the one reference! 

Gap lengths are estimated based on the supplied reference (Looking at a figure in the supplementary information of the biorxiv paper might be clearer than me trying to explain here).

You should use a reference weight >=2 in this case, since you want to trust the reference most. Because those weights are used as edge weights for the minimizer graph, it is expected that you see equivalent results for reference weight >= 2 in this case with your other parameter settings. (See the biorxiv paper for more details about construction/filtering of the minimizer graph).

My understanding here is that you are targeting a particular region that is assembled in a single piece in all your references. I've mostly tested the multiple assembly mode with assemblies that are in varying draft stages, ie. an assembly has joins that another doesn't. In this case, ultimately ntJoin would have to decide to trust one assembly the most to avoid ambiguity, so you will probably get the best results just picking the 'best' reference.

**Comment by ViriatoII** [comment]
I'm sorry, @lcoombe but I think you misunderstood my previous post. 

The good statistics are from ragoo, my ntJoin runs are very far from it, they leave unscaffolded 900 of my original target contigs, while ragoo only leaves 300 unscaffolded.

Maybe the problem is that I'm using unpolished pacbio data. Do you think this breaks your minimizer strategy? Also, the references are from the same species (Maze), but different genotypes, and we expect polymorfisms in our new target genotype (That's why we were interested in using multiple references, to catch polymorfisms that are more related with other genotypes). 

Cheers,
Ricardo

**Comment by lcoombe** [comment]
Hi @ViriatoII,
It is hard to say without having the data and all the information, but it seems like there are areas where contigs are unable to be placed (hence my mentioning the gap-size estimations in my previous post). This could be due to a number of factors such as the size of the pieces vs. your parameter settings, the base variability between the target and the reference, etc. Also, I don't know how you filtered out target contigs, but there could be off-target contigs there, so it is hard for me to interpret the % used in the scaffold (ie. Sometimes using alignments of contigs to just a section of a genome can force alignments).
I haven't tried runs with an unpolished pacbio assembly before, but we show good results using ntJoin with an unpolished nanopore assembly in our biorxiv paper.
If you are willing to share your assemblies with me, I'm happy to take a look.

**Comment by lcoombe** [comment]
@ViriatoII -- I know we've been discussing this via e-mail, but I thought I'd update this ticket with what we talked about so it could help future users.

There appeared to be a few factors that were influencing the amount of sequence being placed and the number of Ns in the output scaffolds. Probably the biggest one is that this is a very repetitive genome, which influences how many 'anchor' minimizers there are for the scaffolds. I found that when you lowered the window size dramatically, this helped with the amount of placed sequence, and was fine for a test of this size. Also, there appeared to be some redudancy in the assembly, and ntJoin will attempt not to place subsumed contigs. The large number of gaps relative to Ragoo is partially related to the fact that Ragoo uses a constant gap size, whereas ntJoin does estimate the gap sizes based on the reference.

We are looking into some updates to the code that should help ntJoin work better for very repetitive genomes, so stay tuned!
