### ISSUE TITLE
Problem with multiple references

### ISSUE THREAD

**Issue by matt-shenton** [bcgsc/ntJoin#37]
Hi there, thanks a lot for this great tool.
I am interested in using 2 references, but the program does not seem to produce any output.

I changed a couple of bases in the test "ref.fa" and called it ref2.fa.
I tried to run as follows:

ntJoin assemble target=scaf.f-f.fa target_weight=1 references='ref.fa ref2.fa' reference_weights='3 2' agp=True

I get output for the first reference, but it seems like ref2.fa is ignored.

make: Nothing to be done for 'ref2.fa'.
make: *** No rule to make target '2'.  Stop.

I wonder if I have misunderstood the description in the README?

Thanks a lot for your help

Matt Shenton

**Comment by lcoombe** [comment]
Hi Matt,

That's strange -- your command looks fine and it works ok on my end. It looks like the quotes aren't being recognized properly on your machine, so that `ref2.fa` and `2` end up erroneously looking like targets for the makefile.

Could you try using double quotes instead and see if that helps?

Thank you for your interest in ntJoin!
Lauren

**Comment by matt-shenton** [comment]
Dear Lauren

Thanks a lot for your quick response.
Your diagnosis seems to be correct - there seems to be a problem interpreting the command.

Double quotes didn't solve it, but if I edit the ntJoin file (the script containing the make command) and include the references and other parameters there, then it runs correctly.

I suppose this may be a locale problem - I am in Japan. I am working on a machine running Centos7. However, I also tried on my macbook (also japanese) and found a similar problem.

Thanks again

Matt

**Comment by lcoombe** [comment]
Hi Matt,

I'm glad you found a work-around! Perhaps it is a locale thing -- the commands with the quotes work for me on centos7, macOS and in a homebrew docker image, so it's a bit difficult for me to troubleshoot on my end unfortunately...
I'll let you know if I come up with a better work-around!

Lauren

**Comment by wuxingbo1986** [comment]
Hi Matt,

I have the exact same issue. I tried your trick but did not work. Do you mind send me the copy of your modified ntJoin file?

I use macOS in conda env. it run well in single reference. Not sure what's wrong with multiple references.

Thanks.
Xingbo

**Comment by matt-shenton** [comment]
Hi Xingbo

The file is as below. I haven't tried it on macOS.
As you see, the version of ntjoin is 1.0.3.

Hope you find it useful
Cheers
Matt

#!/bin/bash
make -f /lustre/home/mshenton/anaconda3/bin/share/ntjoin-1.0.3-0/ntJoin assemble target='naba.scaffolds.fasta' target_weight=1 references='R498_Chr.fasta IR8_genome.fasta' reference_weights='2 3' k=64 w=128 t=4 G=100 agp=True no_cut=True

**Comment by lcoombe** [comment]
Hi @wuxingbo1986 - Feel free to post your command and error, in case that helps us to troubleshoot. I'd be interested to see what the error was on macOS, since I run ntJoin on macOS in a conda environment and haven't seen anything similar.

**Comment by lcoombe** [comment]
Hi @matt-shenton and @wuxingbo1986 ,

I've implemented an option to use a config file to specify the multiple references vs. using a list on the command line, in the hope that this could be a work-around for the issues you were seeing with the quotes.

Since I can't reproduce the error on my side, I'd really appreciate it if either of you would give it a try before I merge the changes to master. The changes are in the branch `config_file`, and there's information in that README with how to use the new option: https://github.com/bcgsc/ntJoin/blob/config_file/README.md#using-a-config-file-to-specify-references-optional

**Comment by wuxingbo1986** [comment]
> Hi Xingbo
> 
> The file is as below. I haven't tried it on macOS.
> As you see, the version of ntjoin is 1.0.3.
> 
> Hope you find it useful
> Cheers
> Matt
> 
> #!/bin/bash
> make -f /lustre/home/mshenton/anaconda3/bin/share/ntjoin-1.0.3-0/ntJoin assemble target='naba.scaffolds.fasta' target_weight=1 references='R498_Chr.fasta IR8_genome.fasta' reference_weights='2 3' k=64 w=128 t=4 G=100 agp=True no_cut=True

Thanks Matt.

**Comment by wuxingbo1986** [comment]
> Hi @matt-shenton and @wuxingbo1986 ,
> 
> I've implemented an option to use a config file to specify the multiple references vs. using a list on the command line, in the hope that this could be a work-around for the issues you were seeing with the quotes.
> 
> Since I can't reproduce the error on my side, I'd really appreciate it if either of you would give it a try before I merge the changes to master. The changes are in the branch `config_file`, and there's information in that README with how to use the new option: https://github.com/bcgsc/ntJoin/blob/config_file/README.md#using-a-config-file-to-specify-references-optional

Hi Lauren,

My error mesage is the same like Matt posted.

I will try the updates and let you know.

Thanks.
Xingbo

**Comment by matt-shenton** [comment]
Hi Lauren,

I gave it a quick try, but I'm finding some other error using v. 1.0.5 vs 1.0.3

I will figure it out, but probably takes a couple of weeks before I have time to troubleshoot properly. Sorry for the delay.

Best wishes
Matt

**Comment by lcoombe** [comment]
Hi @matt-shenton,

Ok thanks for giving it a try! Do feel free to post your error message - there haven't been any major functional changes to ntJoin between 1.0.3 and 1.0.5, so that's strange. I'd be interested if it was perhaps either due to using multi-line fasta files (`indexlr` fails if you do not use single-line fasta files with a full sequence in a single line) or something to do with your environment.

Lauren

**Comment by matt-shenton** [comment]
Hi Lauren,

It's an environment problem, couldn't locate the correct libraries, if I remember correctly. I should be able to figure it out when I give it some time.

Cheers
Matt

**Comment by lcoombe** [comment]
Hi Matt,

Ah I see -- not sure if you're using a conda environment, but just in case there seems to be some sort of samtools/pysam issue right now that I suggested a workaround for here: https://github.com/bcgsc/ntJoin/issues/58

Just mentioning in case that saves you some time when you have a chance to come back to ntJoin! :)
Lauren

**Comment by lcoombe** [comment]
FYI - the new option to specify a config file listing the reference file names and weights (in lieu of using `references` and `reference_weight` variables) was added in release [v1.0.6](https://github.com/bcgsc/ntJoin/releases/tag/v1.0.6)

**Comment by matt-shenton** [comment]
Hi Lauren, Thanks for the update. I will get to testing it soon. Just snowed under at the moment.

Cheers
Matt

**Comment by lcoombe** [comment]
Sounds good, thanks @matt-shenton ! And of course no rush - just hoping that this fix will help you and other users who have the same issue :)
