### ISSUE TITLE
no changes in assembly

### ISSUE THREAD

**Issue by jacorvar** [bcgsc/ntJoin#54]
Hi,

I've run ntJoin with default parameters as in the example and I get exactly the same results as the "raw" assembly in terms of scaffolds. I have tried with several values for `reference_weights` and `k`. The command:

```
ntJoin assemble t=4 time=t prefix=ntjoin target=scaffolds.fa target_weight=1 references='ref.fa' reference_weights='2' k=32 w=500
```

Some context: I have MiSeq data for a gram-negative bacterial species and have assembled it using Spades. My goal is to remove misassemblies and to get a "real" syntheny for the contigs/scaffolds.

Could I have missed something? 

Thanks

**Comment by lcoombe** [comment]
Hi @jacorvar,

Yes, for a reference/target pair the `reference_weight` you've set above makes sense. I would try lower `w` values along with the sweep in `k` values, particularly if you are working with a bacterial species, since it should be running quite fast. 

You could also double check that your installation is working properly with the test here: https://github.com/bcgsc/ntJoin/blob/master/tests/test_installation.sh

Is the `reference` you are using much more contiguous than the MiSeq data? What are the relative contiguities? Are there any joins being made (You can see that in the `path` file), or is it exactly the same as the baseline?

Hope that helps - thanks for your interest in ntJoin!
Lauren

**Comment by jacorvar** [comment]
Hi @lcoombe ,

I've tried `w`  and  `k` values ranging from 20 to 500  and from 10 to 200, respectively, but nothing changes: the final assembly equals the original one. 

My reference is the actual reference genome, so I fully trust it. I have also ran the test and everything seems to be alright, so I cannot understand why there's no change.

Thanks

**Comment by lcoombe** [comment]
Hi @jacorvar,

Yes that is very surprising to me as well.. And the log file looks fine? No errors there?
How contiguous is your target assembly? I'm assuming the reference is in a single piece? Is the reconstruction on-target for your target assembly (ie. no over-assembly)?

**Comment by yangyxt** [comment]
I've met a similar problem. Changing the k value does not alter the result much. 

Here is the summary of number of scaffolds in result. Only the first result is the assigned one, leaving the rest of them unassigned, causing the large number of scaffolds in scaffolding result.
![image](https://user-images.githubusercontent.com/40780228/103202077-71b4e000-492c-11eb-980c-8b2e23891034.png)

**Comment by lcoombe** [comment]
@yangyxt - As I mentioned above, it's important to also do a sweep of 'w' as well as k-values. In fact, I'd expect that the window size `w` to be more important than the `k` value, as it impacts the density of minimizers found in the input assemblies.

Without any information about the particular assemblies (what the draft, references are, is there over-assembly, contiguity, command used, did you try the demo, etc.), it is difficult for me to suggest what could be wrong, like I mentioned in my last comment. Having more information can help me guide you in troubleshooting.
