### ISSUE TITLE
input multiple reference genome failed to parse

### ISSUE THREAD

**Issue by yangyxt** [bcgsc/ntJoin#56]
Here is the command I write:
 
`ntJoin assemble target=assembly_graph_raw_nodes.fasta references='ref1.fasta ref2.fasta' target_weight=1 reference_weights='2 2' k=127 mkt=True agp=True no_cut=True`

According to the log file: 
ntJoin only read the first ref genome and use it for scaffolding in the first round. And it runs smoothly without an error. 
But when it comes to the second ref fasta file. The log says:

```
make: Nothing to be done for 'ref2.fasta'.
make: *** No rule to make target '2'.  Stop.
```

I dunno what went wrong. Pls help, thanks!

**Comment by ardy20** [comment]
Hi I think you may need to rename 'ref2.fasta' to 'ref2.fa'.
eg. mv ref2.fasta ref2.fa
Hope this helps 
Regards
Ardy

**Comment by lcoombe** [comment]
Hi @yangyxt,

It looks like your file system isn't parsing the single quotations properly. So in that case, it is seeing `ref2.fasta` as the name of a Makefile target, instead of part of the `references` variables.

A couple things you can try - I can't test on my end because I don't see the same issue on my local mac machine or on our linux servers: Use double quotes instead of single quotations, or try putting the list of fasta files in a variable, and pass the variable to the command. You can try both with the dry-run option `-n`, which should print out the commands without running them. That will just let you know if the files are being parsed correctly now.

In earlier versions of ntJoin, `.fa` was the only valid suffix for fasta files, but that has been changed now, so it's fine for your fasta files to have the suffix `.fasta`.

I hope that helps, and thank you for your interest in ntJoin!
Lauren

**Comment by lcoombe** [comment]
FYI - a new option to specify a config file listing the reference file names and weights (in lieu of using `references` and `reference_weight` variables) was added in release [v1.0.6](https://github.com/bcgsc/ntJoin/releases/tag/v1.0.6)
