### ISSUE TITLE
conda install the wrong package

### ISSUE THREAD

**Issue by wuxingbo1986** [bcgsc/ntJoin#57]
Hi,

I just installed ntJoin with bioconda. Then I relize it points to a totally different package called make.

ntJoin -h
Usage: make [options] [target] ...

Please check.

Thanks.
Xingbo

**Comment by lcoombe** [comment]
Hi @wuxingbo1986 ,

Please check the `ntJoin` README for information about how to run the program - the issue is not with the bioconda package, but with how you are running the `ntJoin` script. The `ntJoin` driver script is a Makefile which drives each step of the ntJoin pipeline.  `ntJoin help` will print out the help message.

There is also an example of how to run the program and test your installation here: https://github.com/bcgsc/ntJoin/blob/master/tests/test_installation.sh 

Hope that helps and thank you for your interest in ntJoin,
Lauren
