### ISSUE TITLE
Set up paremeters 

### ISSUE THREAD

**Issue by AMMMachado** [bcgsc/ntJoin#60]
Hi @lcoombe,

First of all thank you for this amazing and ultra fast software.

We are working with several genomes, from fish's until mammals with high levels of heterozigoties and repeats.To mitigate these characteristics we have sequenced pacbio Hifi ccs datasets and short reads PE 250 (unfortunately the datasets are from different individuals).  Now we are trying to integrate and use both datasets to improve the base assembly. Briefly, the base assembly it's  a Pacbio Hifi assembly with hifiasm (contig N50,3mb). In addition we have produced others assemblies (of the same pacbio dataset with different parameters). We also have at least 3 short read  assemblies from 250 PE datasets (average 8kb N50). 
Now we are thinking if would be possible to integrate all datasets with the NtJoin. 

Can you clarify some points before ?
The "reference_weights" in the software refers to the importance/order of the assemblies to be used?
Can/should we set both references types (Pacbio based / short read based) in the same run or in sequential / separated runs?
The drafts assemblies should be provided together in a single file (e.g Option 1 - references='Cat_All_Draft_Assemblies.fa' reference_weights='2'), separated (e.g Option 2 - references='A.fa B.fa' reference_weights='2 2'), or interactively (1st run the target genome against the reference A,  2º  run the previous output against reference B ... etc) ?
Should we set up the "no_cut" paremeter, in the last option?
We have done these tests and the results are quite different.
Option 1 - components in graph: 1698 ; 73mb of 815mb assigned.scaffolds (improve of n50, 200kb) .
Option 2 - components in graph: 922 ; 47mb of 815mb assigned.scaffolds (improve of n50, 100kb) .
Are the low values of the assigned.scaffolds expected ?

Best Regards 
André

**Comment by lcoombe** [comment]
Hi Andre,

These are all great questions! Yes, using ntJoin to integrate information from different assemblies is definitely a good use case, and one that we've used within our group a great deal.

`reference_weights`: Correct, it does refer to the relative weights that you give each of the references. That is, if you specify two references with equal weights, you are saying to treat information from the assemblies equally, but if you set one weight as higher, then in cases where the information from the references doesn't agree, you trust the one with the higher weight.

For using multiple references vs. iterative runs -- Often we will try both cases, and go with the approach that gives us the best results (ex. most contiguous, highest complete BUSCOs)! That isn't normally too time-consuming since ntJoin usually runs quite quickly.
So for example, if you have a target assembly, and references A, B, and C:
1. Multiple assemblies -- specify `references="A.fa B.fa C.fa"`
2. Iterative runs:
* Target + `references=A.fa` => output_1
* output_1 + `references=B.fa` => output_2
* output_2 + `references=C.fa` => final output

Using all the assemblies concatenated together isn't recommended, just because of how repetitive minimizers are filtered out from assemblies.

Since you are working with a fairly repetitive genome, you could try using lower values of `w`, which can often help with assigning more scaffolds. However, seeing lower % assigned isn't necessarily a cause for concern since you are working with a fairly contiguous assembly to start with. Any contig that is _not_ joined to any other pieces in the ntJoin run is considered 'unassigned' - so these pieces could just be sequences where the reference assembly (or assemblies) don't have any extra information in that genomic location.

For the `no_cut` option -- The choice for that parameter really depends how much you trust the structure of your baseline assembly. If you want to retain all the joins that are already in that assembly, it's a good idea to set `no_cut=True`, but if you trust the structure of the reference(s) more, then you could not set that. Either way should work well in your case.

I hope that helps, and thank you for your interest in ntJoin!
Lauren

**Comment by AMMMachado** [comment]
Hi @lcoombe,

Thank you so much for the speedy response and the valuable informations. 

We have performed several tests per reference (multiple k 15, 17, 19, 21, 24, 27, 32 and w 50, 100, 250, 500, 750, 1000, 1500, 2000)  and the results are quite similar, at contiguity and busco level( N50 increasing 300-400kb (per interaction) / and 1-2% buscos in the total). In general the interactive runs showed better results than multiple assembly approach. 
Once the contiguity and busco are very similar, we are considering to use the (higher number linked scaffolds / lower number of gaps ) parameters to choose the best assembly per interaction. Additionally, to do this choice we intend to use all the possible combinations of the parameters above mentioned. We are using the no_cut=true in all the process.
 What you think about this strategy? 
Can this strategy increase significantly the number of mis-assemblies?
Should we use always the same K and W in all interactions, or can we change it per interactions without influence "negatively" the final results ?
Additionally we performed the scaffolding of our assembly against a close related species with n50 =7mb. Surprisingly our assembly increased the n50 from 3mb to 20mb and the buscos from 96 to 99 % complete.  Both species belongs to the same sub-family and the divergence time between both species its around 35M years. Do you have or know some tool to evaluate the bias introduced in the assembly by using a ref-based approach? 

Best Regards
André

**Comment by lcoombe** [comment]
Hi Andre,

I think your approach makes sense! Generally, when I'm deciding on the best assembly per an iteration, I would tend to pick the assembly that has the highest NG50/complete BUSCOs, and perhaps use the number of scaffolds as a tie-breaker, but I think there are multiple metrics that would be just fine. Also, if the results from the different parameter combinations are quite similar, then which of those assemblies you move forward with will likely not have a huge impact on the quality of your final results. I think it's fine to use different k/w for each iteration, as long as you just have that metric that you use for deciding on which one to move forward with -- just so the choice is defendable. 

One thing I would just be careful of is not going too low with the `k` value - I think that your choices are OK, but I probably wouldn't go quite as low as 15 - 17 should be fine. That's just because the lower values get less specific.

That's a great result seeing the N50/BUSCO improvement of the assembly using the closely related species! We have seen cases where the final assembly has a higher contiguity than the reference -- see Fig 1 of the ntJoin paper. Unfortunately, I don't know of a tool to assess reference bias - I usually rely on reading papers to get a sense of how structurally similar the genomes are expected to be.

Hope that helps!
Lauren
