### ISSUE TITLE
Chromosome order after scaffolding

### ISSUE THREAD

**Issue by NTNguyen13** [bcgsc/ntJoin#63]
Hi, I'm quite happy with the result and capability of ntJoin that it can integrate multiple references for scaffolding. However I also want to keep the original reference chromosome name, or at least know which the newly-created scaffold come from. At this moment, I just have tried 1 reference, 1 target case: the scaffolded chromosomes are named `nt*`, and I'm not quite sure about the related order of its and the reference's. And how's about multiple reference cases? How should I interpret the order of the chromosomes? 

Thank you very much.

**Comment by lcoombe** [comment]
Hi @NTNguyen13,

Yes, no matter how many references you use for scaffolding the newly-created scaffolds ntJoin will be named `ntJoin*`, as you observed.
If you want to see what contigs were joined using the information from the specified reference(s), you can either look at the output `.path` file, or set `agp=True` to output an agp file describing the makeup of the output scaffolds.
From either, you can see the names of your target contigs plus the corresponding coordinates (if you have `no_cut=False`, then the input target scaffolds may be cut), and the sizes of the introduced gaps.

I hope that helps, and thank you for your interest in ntJoin!
Lauren

**Comment by NTNguyen13** [comment]
Hi, I have checked out the *.path and *.agp file, and I saw how each newly-created scaffold made from the target contigs. However I want to know the relationship between the new scaffolds and the reference chromosomes. For example, I want to scaffold de novo assembly contigs into hg38, I want to know how the ntJoin0 related to chr1, and so on.

**Comment by lcoombe** [comment]
Hi @NTNguyen13,

ntJoin uses a lightweight minimizer-graph approach to map the target to the reference sequence(s). To create the paths that you see in the path and agp files, we filter the graph, then traverse the linear paths in this graph. So, it would require some parsing on your end depending what detail of information you want, but that mapping information of target contigs to reference is in the dot file (`*mx.dot`). Here, the nodes are minimizers (which contain the associated contig/position of the minimizer for the target contigs and reference(s)), and edges are created between minimizers that are adjacent in at least one of the input assemblies. So you could potentially use that to find the reference(s) that a given target contig from your output scaffolds mapped to.
There's more information about the minimizer graph in the paper: https://doi.org/10.1093/bioinformatics/btaa253

**Comment by NTNguyen13** [comment]
Thank you for your answer. I will research more on this problem :+1: 

A bit off-topic, I want to know how the result in the original paper are produced. From the Supplementary documents, I found this
```
...All human assemblies were
scaffolded with ntJoin using the GRCh38 build of the human reference genome (v1.0.2; t=4,
target_weight=1, reference_weights=’2’, n=2) with a sweep of k and w.
We subsequently used ntJoin to scaffold a short read H. sapiens assembly using a draft long read H.
sapiens assembly as the reference. For this test, we used the H. sapiens (NA12878) ABySS assembly
scaffolded with MPET data as the target assembly and the Shasta assembly with and without polishing
as the reference assembly (v1.0.2; t=4, target_weight=1, reference_weights=’2’, n=1) (Table S1).
```

As I understand, there are 2 major cases:
- Case 1: assembly by using short reads and then scaffolding using GRCh38 as reference. Parameter: t=4, target_weight=1, reference_weights=’2’, n=2. k and w is swept.
- Case 2: assembly by using short reads and then scaffolding using a draft long read as reference. Parameter: t=4, target_weight=1, reference_weights=’2’, n=1.

I have some questions:
- In case 1, what is the best k & w combination after QC by QUAST? Using Figure S8 and S9, it seems like the k=32 is the "sweet spot". While for w, the colors are a bit similar between 1500 and 2000, but I think that they are similarly good enough.
- In case 2, I suppose that k & w are using the best parameter from case 1, which is I didn't know for sure.

Could you please clarify this for me? Many thanks

**Comment by lcoombe** [comment]
Hi @NTNguyen13,

Yes those are the two main cases that we talk about in the paper! We also show scaffolding a long read assembly with a reference. That's the nice thing about ntJoin - it can be useful for a lot of different scenarios, as long as you have a target assembly that you want to contiguate, and at least one reference (which can be true reference-grade or a draft assembly).

Generally, the main takeaway from the results of parameter sweeps is that the algorithm is generally not too sensitive to the k or w parameters. I usually start with the default k/w, and will do some limited sweeps (you can see the sort of values we try based on the supplementary tables and figures), and pick the 'best' assembly from those sweeps. Depending on your situation and the species being assembled, you can assess using QUAST or simply NG50/BUSCO results.
Supplementary Table S14 shows the k/w parameter sweeps for case 2, and in that case we considered the 'best' assembly to use k=32, w=1500 - so once again similar to case 1, and close to the default parameters.

As for the 'n' change - that's due to case 1 using a true reference-grade assembly for reference, vs. case 2 using a draft assembly as reference. In case 1, you don't expect there to be any joins in the draft that are _not_ in the reference, but that isn't necessarily true for case 2. So you would expect there to be possible joins that are _only_ supported by the draft in case 2, but not in case 1. I mention this briefly in the README, but don't really go into detail about the intuition: https://github.com/bcgsc/ntJoin/#parameter-considerations

Hope that helps!
Lauren

**Comment by NTNguyen13** [comment]
Many thanks!
